#!/bin/bash

# Check that only one argument is used
if [ $# -ne 1 ]
then
  echo "only ONE integer allowed as argument"
  exit
fi  

# Argument 
delta=$1

max=$(sudo cat /sys/class/backlight/intel_backlight/max_brightness)
# User-defined min
min=$((10))

# echo 'max brightness is' $max
current=$(sudo cat /sys/class/backlight/intel_backlight/brightness)
# echo 'current brightness is' $current
new=$((current+delta))
if (( $new >= $max )); then
  new=$max
  echo 'max brightness reached' $new
elif (( $new <= $min )); then
  new=$min
  echo 'min brightness reached' $new
fi
# echo 'new brightness is' $new
echo $new | sudo tee /sys/class/backlight/intel_backlight/brightness > /dev/null
