#!/bin/bash
# Resizes video and converts them to animated gifs
# 1st arg : filename
# scale : numero lineas , eg 480
# fps : con 6 va bastante fluido, big file, probar
# el split y esa mierda es para la paleta de color
video=$1

# FUNCIONA DE LUJO! poner a 480p para que no se haga demasiado grande
ffmpeg -i $video \
-filter_complex "[0:v] fps=4,scale=w=-2:h=$2,split [a][b];[a] palettegen [p];[b][p] paletteuse" "${video%.*}.gif" \

# ffmpeg -i $video \
#   -r 10  \
#   -f image2pipe \
#   -vf scale=640:-1 \
#   -vcodec ppm - | \
#   convert \
#   -delay 10 \
#   -loop 0 - output.gif


