#!/bin/bash
current=$(sudo cat /sys/class/backlight/intel_backlight/brightness)
new=$((current-25))
if (( $new <= 0 )); then
  new=$max
  echo 'min brightness reached' $max
fi
# echo 'new brightness is' $new
echo $new | sudo tee /sys/class/backlight/intel_backlight/brightness > /dev/null
