#!/bin/sh
REPOSITORY=~/borg.backups

# Setting this, so you won't be asked for your repository passphrase:
# export BORG_PASSPHRASE=''
# or this to ask an external program to supply the passphrase:
# export BORG_PASSCOMMAND='pass show backup'

# Backup all of /home and /var/www except a few
# excluded directories
borg create -v --stats                          \
    $REPOSITORY::'{hostname}-{now:%Y-%m-%d}'    \
    ~/Pictures/                                 \
    --exclude '~/Pictures/*.JPG'
    # --exclude '*.pyc'

# Use the `prune` subcommand to maintain 7 daily, 4 weekly and 6 monthly
# archives of THIS machine. The '{hostname}-' prefix is very important to
# limit prune's operation to this machine's archives and not apply to
# other machine's archives also.
# borg prune -v --list $REPOSITORY --prefix '{hostname}-' \
    # --keep-daily=7 --keep-weekly=4 --keep-monthly=6
