#!/bin/bash
# For some reason the initial solution is not working so lets hack the way into it

sensitivity=220
speed=100

# /sys/devices/platform/i8042/serio1/serio2/sensitivity
# /sys/devices/platform/i8042/serio1/serio2/speed
# /etc/udev/rules.d/trackpoint.rules

echo $sensitivity | sudo tee /sys/devices/platform/i8042/serio1/serio2/sensitivity > /dev/null
echo $speed       | sudo tee /sys/devices/platform/i8042/serio1/serio2/speed > /dev/null
