#!/bin/bash
# The range of the quantizer scale is 0-51: where 0 is lossless, 23 is default, and 51 is worst possible. A lower value is a higher quality and a subjectively sane range is 18-28. Consider 18 to be visually lossless or nearly so: it should look the same or nearly the same as the input but it isn't technically lossless.

video=$1
# echo "Does this work ? " "${video%.*}"_encoded."${video##*.}"
ffmpeg \
  -i $video \
  -c:v libx264 \
  -preset medium \
  -crf $2 \
  -c:a copy \
  "${video%.*}"_encoded."${video##*.}" \
  -report
