#!/bin/bash
# -vf "transpose=2"  rotates 90 counter-clockwise
# -vf "transpose=1"  rotates 90 clockwise
# ATENCION ! : parece que hace algo de compresion, el tamanyo se reduce muchisimo !!!!

video=$1

# ffmpeg \
#   -i $video \
#   -vf "transpose=2" \
#   -c:a copy \
#   "${video%.*}"_rotated."${video##*.}" \
#   -report

# an : no audio. pensado para hacer gif. 
ffmpeg \
  -i $video \
  -vf "transpose=2" \
  -an \
  "${video%.*}"_rotated."${video##*.}" 
